version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

  nextjs:
    build: .
    container_name: iron-nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules      

volumes:
  data:      